### ISSUE TITLE
edit aix stanza files

### ISSUE THREAD

**Issue by flynn1973** [aixoss/ansible-playbooks#16]
quick question concerning aix and ansible.  i am struggling with editing (add, update,delete) of aix stanza files with ansible. i looked over the lineinfile and blockinfile modules but i it seems they are not the best for this job. any ideas? have you ever done this successfully?

**Comment by robinvy** [comment]
Hi, no I haven't needed to change an aix stanza file with Ansible so far.

**Comment by gforster** [comment]
I was looking at writing a module for this based on the ini module as they are so similar, but haven't gotten around to that yet. Or maybe we can convice IBM to start using yaml :-)

**Comment by flynn1973** [comment]
not relevant anymore...closing

**Comment by gforster** [comment]
curious why this is no longer relevant? It is something that I could definitely use, just haven't had time to develop.

**Comment by flynn1973** [comment]
look here -> https://github.com/ansible/ansible/pull/60976 ;-)

**Comment by pinacoelho** [comment]
Well,
chsec only operates on a pre-set list of predefined files.
I've landed here because I was trying to change a stanza file that is not on chsec's predefined list (namely /etc/security/audit/config).

**Comment by flynn1973** [comment]
files not  in the chsec allowed list are not meant to be edited by end users

**Comment by pinacoelho** [comment]
I don't understand what you're saying.  /etc/security/audit/config isn't in the allowed list, but it's certainly a file you're supposed to edit to setup auditing.

**Comment by flynn1973** [comment]
ah sorry,  what i would say is " are not meant to be edited by the chsec ansible module"
feel free to participate here -> https://github.com/IBM/ansible-power-aix/issues/164
